server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: 'pxO[{yNZLtxIJSyOb}rdIAYyiJrJQKiGnsnIilQhVWM6ZDRIcnn99I+FJG0D'


